application: dojofit-dev
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: .*
  script: dojofit.app

libraries:
- name: webapp2
  version: "2.5.1"
